### ISSUE TITLE
how can I make it run?

### ISSUE THREAD

**Issue by beckmx** [aborilov/pymdb#1]
Hello, It looks interesting the code, I was wondering how can I test it?

**Comment by aborilov** [comment]
Hi, you can look at https://github.com/aborilov/kiosk, I use this protocol there, but it is very early version. If you have any question, pls write.Will try to write some examples later.

**Comment by beckmx** [comment]
I was looking at the parity bits of the serial but they are 8 I believe it
should be 9

**Comment by aborilov** [comment]
I found this in NRI documentation:
If you would like to operate an NRI changer using the RS-232 interface, you need to know the settings to open the RS-232 port, in order to be able to apply the NRI PC protocol (see Chap. 4):

```
Baudrate: 38400 
Byte size: 8 
Parity: no 
Stop bits: 1
```

**Comment by beckmx** [comment]
:o okay that's wierd I was looking at the vending.org specification

2016-01-13 11:27 GMT-06:00 Pavel notifications@github.com:

**Comment by aborilov** [comment]
Because this is not MDB, MDB can't be use through RS232. This is NRI MDB protocol, it can be used with NRI device
